### PR TITLE
adding js-enabled feature tests for representative media

### PR DESCRIPTION
**Pull request by jenlindner**
This PR intends to test that the file designated as representative-media stays that way even if the user uploads more than one file or adds files later. (Please review, @mark-dce, to make sure I'm testing the right things.) It employs javascript-enabled feature tests to do this. It also contains a small test to ensure a Hyrax::Uploaded file gets created. There's a different, inline way of cleaning up employed in some tests, that I like because it seems more reliable, makes each test less abstracted and more complete on its own. 

It relies on sleep(2) in several places to let the browser's js catch up, and that's not ideal. But I feel like it's a solid step forward.

### CODE REVIEW

**Review by mark-dce — DISMISSED** [review]
This looks right to me 👍

**Comment by jenlindner** [comment]
Thanks @mark-dce

**Comment by little9** [comment]
@jenlindner could you take the changes that you made to the autocomplete test and make a separate PR if it's going to be a while before this one is merged?

**Review by little9 — DISMISSED** [review]

**Comment by jenlindner** [comment]
Yes, a separate PR for the autocomplete on the way, @little9.

**Comment by jenlindner** [comment]
Hey @no-reply, I rebased this and cleaned it up a little, and it's green. Let me know what you think.

**Review by no-reply — APPROVED** [review]
This looks excellent! Nice work! :dancer:

**Pull request merged**
