### PR TITLE
using chromedriver for javascript driver in feature tests

### PR DESCRIPTION
**Pull request by jenlindner**
This commit installs Chromedriver as our Javascript test driver, for a few reasons. The first is that Hyrax uses this driver, and therefore it keeps Mahonia better aligned with a baseline Hyrax installation. For development purposes, it greatly improves our ability to write and debug our feature tests by being able to see them run in a browser, stopping execution wherever desired with a byebug to examine the page state. We follow the Hyrax example of keeping our Rack test driver for non-Javascript feature tests, which we use to test downloading files because that driver has header-checking methods specifically for this purpose. And for CI testing, it speeds up tests a bit.

Installing it is a matter of installing the Chromedriver-helper gem and configuring the rails_helper and travis settings.

`# Gemfile
gem "chromedriver-helper"`

```ruby
# rails_helper.rb

Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end

Capybara.javascript_driver = :selenium_chrome
```

We made one additional modification to the rails_helper, to keep the browser window a large enough size to prevent content from getting inadvertently hidden:

```ruby
config.before(:each, type: :feature) do
    # Note: Make browser huge so that no content is hidden during tests
    Selenium::WebDriver::Remote::Capabilities.chrome(
      chromeOptions: { args: %w[window-size=2500,2500] }
    )
  end
```

Travis required a few configurations on top of the basic Hyrax setup, for better memory management with our longer feature tests.

```ruby
  # travis.yml

    addons:
      apt:
        packages:
        - qt5-default
        - libqt5webkit5-dev
        - gstreamer1.0-plugins-base
        - gstreamer1.0-tools gstreamer1.0-x
        - google-chrome-stable

    before_install:
      - gem update --system
      - gem install bundler
      - google-chrome-stable --headless --disable-gpu -no-sandbox --browsertime.xvfb --remote-debugging-port=9222 http://localhost &
      
      script:
        - xvfb-run -a bundle exec rake ci
```

### CODE REVIEW

**Review by little9 — APPROVED** [review]
👍 👍 👍 

The only caveat with this is that makes testing a file download more complicated, see:
https://collectiveidea.com/blog/archives/2012/01/27/testing-file-downloads-with-capybara-and-chromedriver

There was a test in epigaea that tested downloading a file, so I didn't want to do this on that project. If we think we'll need to test that we should think about a solution.

**Review by little9 — CHANGES_REQUESTED** [review]
@jenlindner it looks like there might be additional setup required:

```
     Failure/Error: visit '/concern/etds/new'
     
     Selenium::WebDriver::Error::UnknownError:
       unknown error: Chrome failed to start: exited abnormally
         (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.6-040906-generic x86_64)
```

**Comment by jenlindner** [comment]
That's the autocomplete test, which has a seemingly intermittent error in it due to setup/teardown, looks like; I think this is just how chromedriver reports that error, not that it needs more setup, because the rest of the suite runs okay.

There's a fix for that error in the other PR, it seems to pass consistently locally with inline setup & teardown. I think one key aspect is using find or create the admin set after the clean at the beginning of the tests and if that proves true it might be good to include in the rails helper.

https://github.com/curationexperts/mahonia/blob/dc42ea84552722c4445a18cf7fd3717b90b76420/spec/features/autocomplete_mesh_spec.rb#L10-L11

**Comment by jenlindner** [comment]
@little9 We test downloading a file here, in the access_an_etd feature test, and it's js: false, so we use the rack driver and use its methods to check the headers. We could leave that as it is until or if we decide to something more robust.

**Review by little9 — DISMISSED** [review]

**Comment by little9** [comment]
@jenlindner is this failing for you locally or is this a travis issue?

**Comment by jenlindner** [comment]
@little9 It's a Travis issue. But why :( 

I'm going to run it headless locally and see what happens, up to now only using the browser there.

**Comment by jenlindner** [comment]
@little9 It was the headless factor. It changed the timing on certain tests. I'm not sure if the following things will fix things in Travis, but they might, they do for me locally.

I decided to use a while loop in edit situations with the condition being that the record doesn't exist, instead of just sleeping, and changed the order of metadata form tabs filled out in the edit and autocomplete tests, because moving from the bottom of the page in the Description tab and back to the top to click the Files tab and then back down to the Save button is just too tricky to time correctly. With this flow of execution, the browser is in a state where the elements we need to be clickable are consistently clickable when the test needs them to be. If this seems reliably stable, maybe it should be our de facto practice for all of our feature tests.

My hope with this driver PR is that we can use the browser for writing tests and then run them headlessly in Travis, and have tests that are solid in both cases.

**Comment by jenlindner** [comment]
I found info about this in an issue on Travis's github page, and another link. Seems to have to do with memory and handling the headless output. 

https://github.com/travis-ci/travis-ci/issues/7150
https://github.com/sitespeedio/sitespeed.io/issues/1471

**Review by little9 — DISMISSED** [review]

**Review by little9 — APPROVED** [review]

**Pull request merged**
